### ISSUE TITLE
Create Impressum

### ISSUE THREAD

**Issue by bstkr** [bstkr/interactive-movie#1]
Create simple impressum

make it look like the home page
- no final styling for now

**Comment by pikser** [comment]
Keine Ahnung, wie die gitignore reingerutscht ist. Falls du noch irgendwie images von den jeweiligen Personen haben willst und dann die Daten einfach alle drunter packen können wir ja noch bereden. Ich habe noch bisschen gerätselt, da ja in nem Impressum immer auch ne Adresse und Telefonnummer steht auch da was zu machen aber wir sind ja kein richtiges Unternehmen.

**Comment by Tobias-VA** [comment]
Joa wenn wir nen Impressum machen, sollten da dann meine Daten rein wenn ich des dann hoste oder?

**Comment by vj-14** [comment]
Bilder von unserem Team kommen eigentlich auf die Credits Seite

**Comment by bstkr** [comment]
Das wichtige ist erstmal, dass ein Impressum da ist. Der Inhalt und das Styling wird alles noch beredet. (Montag)
