### ISSUE TITLE
Einkaufszettel decision

### ISSUE THREAD

**Issue by Tobias-VA** [bstkr/interactive-movie#164]
Einkaufszettel wird auch angezeigt wenn man nicht einkaufen geht, sollen wir da evtl irgendwas anderes einblenden oder so lassen?

**Comment by bstkr** [comment]
Konnte ich nicht reproduzieren bei mir ist kein Einkaufszettel im Zimmer, wenn ich mich für nicht einkaufen entscheide

**Comment by Tobias-VA** [comment]
Äh hab das wohl bisschen schlecht beschrieben Sorry, meine bei deine Entscheidung das Große Bild.
