### ISSUE TITLE
Add an item component

### ISSUE THREAD

**Issue by bstkr** [bstkr/interactive-movie#22]
Add a component where the item that has been chosen in the video scene will be shown after the scene was played.

- The item should be displayed over the whole screen after the video sequence is finished
- The user can close the item by clicking on it
- The selected item should the be displayed on the background instead of the interaction

**Comment by bstkr** [comment]
*THIS WILL BE A LINK*

Bitte beim Export dann die bilder maximal halb so groß machen von der Auflösung, damit die nicht so groß sind... sind ja momentan fast 3GB!

**Comment by vj-14** [comment]
Also dann mach ich Zeitung, Vorladung, Hose nass und trocken

**Comment by Tobias-VA** [comment]
Laptop macht glaub nicht so viel Sinn oder? Da gehts ja eher um den Bildschirminhalt?

**Comment by pikser** [comment]
Dann mach ich einfach so weiter und nehme die beiden Nummern (Serviette, Zettel), Jacke und Laptop (falls Laptop doch nicht, dann lassen wir das)

**Comment by Tobias-VA** [comment]
Macht das Item Komponent überhaupt Sinn? Bin her grad dran des Einzubauen, aber irgendwie hat das keinen Mehrwert für die Anwendung, Man sieht ja nach der Sequenz eh das geänderte Objekt im Raum, und wenn man das nochmal anklickt kommt man ja in die Videokomponente. Des weiteren sind unsere Objekte jetzt nicht so spannend das man die in ner Nahaufnahme braucht bis auf vlt. die Zeitung. Find auch des wirft einen irgendwie raus wenn nach der Filmsequenz so nen großes Objekt angezeigt wird. Könnt man sich ja nochmal überlegen ob wir des wirklich wollen.
Wie seht ihr das?

**Comment by bstkr** [comment]
Ich will dem User auf jeden Fall zeigen für was er sich entschieden hat und dafür baust du die item component. Wenn das dann störend wirkt kann man sie immernoch anders designen.

**Comment by Tobias-VA** [comment]
Ok gut, dann mach ich mal weiter, dann können wir ja immer noch schauen.

**Comment by Tobias-VA** [comment]
Kann bitte jemand, das Kaputte Bier ausschneiden?
Hab grad 1,5h Des 5 mal ausgeschnitten und rumprobiert, aber mein Programm stürzt jedes mal ab wenn ich des Exportieren will und die Speicherdateien sind alle Kaputt wo das Bild drin ist, das hat anscheinend irgend ein Fehler mit dem der hier nicht klar kommt...

**Comment by vj-14** [comment]
Ok kann ich morgen machen bzw. hol dir doch einfach mal Photoshop ;)
