### ISSUE TITLE
Cut out Objects

### ISSUE THREAD

**Issue by bstkr** [bstkr/interactive-movie#3]
Download .tif files of pictures

Cut out objects in relation to eachother

https://we.tl/t-vHErp6sSvT

**Comment by bstkr** [comment]
@Tobias-VA 
Ich hab es jetzt geschafft mal eine interaction so zu gestalten wie ich sie mir vorgestellt habe.
Hier findest du das Grid, das is dafür verwendet hab. https://github.com/bstkr/interactive-movie/commit/278072cb91453490a40610aa16dc9c3359768a91
Hab das dann einfach so klein wie möglich um die Objekte gelegt.

**Comment by Tobias-VA** [comment]
Würde dann alle Objekte aus POV 1 ausschneiden. Falls sich noch wer daran beteiligen will POV 2 und 3 sind dann noch zu erledigen.

**Comment by vj-14** [comment]
Ok dann fang ich mal mit den Objekten aus POV 3 an

**Comment by bstkr** [comment]
@pikser bitte POV 2 Objekte ausschneiden. Kannst dich ja mit @Tobias-VA und @vj-14 abstimmen, wenn die fertig sind können die auch objekte in POV 2 machen.

**Comment by bstkr** [comment]
@All Mir ist gerade aufgefallen, dass nachdem der User sich entschieden hat, das Objekt nicht mehr wechseln sollte. Siehe #22 
Dafür brauchen wir dann auch jeweils die kompletten Objekte (nicht mit dem grid zerschnitten).
Ladet doch bitte noch die Objekte in die jeweiligen ordner als "complete.png".

**Comment by Tobias-VA** [comment]
@bstkr Hab jetzt glaub alle cutouts von pov1, oder fehlt da noch was? Und passt des jetzt so hab versucht des aufzuhellen ohne das es unnatürlich aussieht.

**Comment by vj-14** [comment]
@bstkr Bin mit den Objekten aus pov3 fertig. Vll. mal kurz drüber schaun, ob des so passt.

**Comment by bstkr** [comment]
@Tobias-VA @vj-14 Sieht gut aus, werde heute abend versuchen die einzubinden.

**Comment by bstkr** [comment]
@Tobias-VA In POV1 fehlt noch das Handy als interaction. Das ist ja glaub die aller erste Interaction oder?

**Comment by Tobias-VA** [comment]
@bstkr Ja das Handy verändert sich aber nicht oder? Da müssten wir des irgendwie anders machen weil wenn sich das ausblendet macht das ja keinen Sinn oder?

**Comment by bstkr** [comment]
@Tobias-VA Ja stimmt. Kannst du versuchen über das Handy einen weißen Screen zu legen?

**Comment by Tobias-VA** [comment]
@bstkr Sowas hier in etwa? [](http://puu.sh/Fpe52/eddfa0addf.jpg)

**Comment by bstkr** [comment]
@Tobias-VA sieht gut aus 👍🏾

**Comment by Tobias-VA** [comment]
Willst du das als Overlay, oder direkt im Bild?

**Comment by bstkr** [comment]
Wieder als zwei Varianten einmal in weiß einmal in schwarz, dann müssen wir da keine extra Animation machen

**Comment by Tobias-VA** [comment]
Objekte sollten alle ausgeschnitten und vorhanden sein.
