### ISSUE TITLE
Wrong laptop image in item component after decision

### ISSUE THREAD

**Issue by Tobias-VA** [bstkr/interactive-movie#91]
Items Vertauscht aber nur im Item Component nicht im pov

**Comment by Tobias-VA** [comment]
Und in der Timeline ist es auch vertauscht

**Comment by bstkr** [comment]
Bei mir ist es nur in der Item Component falsch

**Comment by Tobias-VA** [comment]
Also bei der Trink Entscheidung ist Item & Timeline falsch, bei der Tanz Entscheidung nur die Item component

**Comment by bstkr** [comment]
Ich hab die trink entscheidung durch gemacht und das timeline bild war richtig.
Sieht man auch wenn man die bilder aufmacht:
Objects: Laptop_1 = Tanzen Laptop_2 = Trichter
Timeline Objects: Laptop_1 = Trichter Laptop_2 = Tanzen
POV1: object8 [Entscheidung 1] = Trichter object9 [Entscheidung 2] = Tanzen
POV2: object8 [Entscheidung 1] = Trichter object9 [Entscheidung 2] = Tanzen

Habe jetzt einfach die Item component zuordnung umgedreht
