### ISSUE TITLE
Einkaufszettel is missing in pov1

### ISSUE THREAD

**Issue by Tobias-VA** [bstkr/interactive-movie#92]
Der Einkaufszettel fehlt nach der Entscheidung einkaufen zu gehen in pov1

**Comment by bstkr** [comment]
Komisch ist bei mir nicht der Fall. Kuck mal ob du das reproducen kannst und ob was in der console steht...

**Comment by Tobias-VA** [comment]
Jo ist reproduzierbar , aber nur bei der Version auf dem Server, einfachdie Einkaufs Alternative anklicken. Lokal / bei dem aktuellen Master scheint alles zu passen.
